locations = [
"Kensington Gardens",
"Grosvenor Street",
"Cytherea Gallery",
"Royal Opera House",
"King’s Theatre",
"Gentleman Jack’s",
"Gunter’s",
"Mayfair Ice Cream Parlour & Café",
"Queen Anne’s Lace & Silk",
"Lady May’s",
"The Silver Lantern",
"The Amorous Bloom",
"Mayfair Boxing Club",
"Mayfair Cutlers & Smiths",
"Pâtissierie à Mayfair"]
